# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel's bioinformatics blog
email: gabriel.reno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Different musings about bioinformatics, coding and sustainability 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gabrielylr
github_username:  grenaud

load_paths:
 - _sass
  
# Build settings
markdown: kramdown
